**Pandas** — это центральный узел (хаб) в мире Data Science.\
Данные загружаются и очищаются в pandas.\
Математические операции проводятся через NumPy.\
Визуализация строится через Matplotlib или Seaborn (которые понимают объекты pandas).\
Модели машинного обучения (Scikit-learn, TensorFlow) обучаются на данных, подготовленных в pandas.

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

# Series (Серия)
— это одномерный массив данных, у которого есть метки (индекс).

In [ ]:
# Создание Series из списка (List)
data_list = [10, 20, 30, 40]

series_from_list = pd.Series(data_list) # Превращаем в Series
print(series_from_list)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# Создание Series с собственным индексом
sales = [150, 200, 100] # Данные - продажи
months = ['Jan', 'Feb', 'Mar'] # Индекс - месяцы

s = pd.Series(sales, index=months) # Явное указание индекса
print(s)

Jan    150
Feb    200
Mar    100
dtype: int64

In [ ]:
# Создание Series из словаря (Dictionary)
currencies = {
    'USD': 92.5,
    'EUR': 99.1,
    'CNY': 12.8
}

s_curr = pd.Series(currencies) # Pandas автоматически поймет, что ключи — это индексы

print(s_curr)

USD    92.5
EUR    99.1
CNY    12.8
dtype: float64

In [ ]:
# Параметр name
#У Series есть полезный атрибут name. Это имя всей серии (будущее название колонки, если мы объединим несколько серий в таблицу).

s = pd.Series([10, 20, 30], name='Temperature')
print(s)

0    10
1    20
2    30
Name: Temperature, dtype: int64

In [ ]:
#Записи ниже обращаются к одному и тому же элементу
s_curr[1] # Обратиться по неявной позиции
s_curr['EUR'] # Обратиться по явной метке

/tmp/ipykernel_4618/1470711114.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_curr[1] # Обратиться по неявной позиции

np.float64(99.1)

**!!!** Если явный индекс состоит из целых чисел, pandas при использовании квадратных скобок [] ищет ***только явную метку***. Как избежать путаницы? (loc и iloc)\
**.iloc[]** (Integer LOCation) — всегда смотрит на неявный позиционный индекс (0, 1, 2...).
`s_years.iloc[0] -> вернет 500 (первый элемент).`\
**.loc[]** (LOCation) — всегда смотрит на явный индекс (метку).
`s_years.loc[2010] -> вернет 500.`

In [ ]:
import pandas as pd

cities = pd.Series([12000, 8500, 5000],
                   index=['Moscow', 'London', 'Paris'],
                   name='Population')

In [ ]:
cities.values # атрибут возвращает «сырые» данные серии

array([12000,  8500,  5000])

In [ ]:
cities.index # атрибут возвращает объект индекса — список наших меток
# Без явных меток, индекс выглядел бы иначе:
# RangeIndex(start=0, stop=3, step=1)

Index(['Moscow', 'London', 'Paris'], dtype='object')

In [ ]:
cities.dtype # атрибут показывает, данные какого типа хранятся в серии

int64

In [ ]:
cities.name # У самой серии может быть имя. Когда мы будем объединять несколько серий в таблицу (DataFrame), имя серии станет названием колонки.

'Population'

# DataFrame (Датафрейм)
— это двумерная табличная структура данных.\
Технически DataFrame — это набор объектов Series, у которых общий индекс.\
У нас есть две оси: 0 (строки) и 1 (столбцы).

In [ ]:
# создание DataFrame из словаря списков (Dict of Lists).
# При этом важно чтобы все списки значений словаря должны быть одинаковой длины.
data = {
    'Name': ['Anna', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Moscow', 'London', 'Paris']
}

df = pd.DataFrame(data)
print(df)

      Name  Age    City
0     Anna   25  Moscow
1      Bob   30  London
2  Charlie   35   Paris

In [ ]:
# создание DataFrame из списка словарей (List of Dicts). JSON-стиль
# Каждый словарь — это одна строка. Ключи словарей становятся колонками.
data = [
    {'Name': 'Anna', 'Age': 25, 'City': 'Moscow'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35}  # У Чарли нет города!
]

df = pd.DataFrame(data)
print(df)

      Name  Age    City
0     Anna   25  Moscow
1      Bob   30  London
2  Charlie   35     NaN

In [ ]:
# создание DataFrame из писка списков (List of Lists) или Массив NumPy
# Имена колонок нужно передать отдельно через параметр columns.
raw_data = [
    ['Anna', 25],
    ['Bob', 30],
    ['Charlie', 35]
]

df = pd.DataFrame(raw_data, columns=['Name', 'Age'])
print(df)

      Name  Age
0     Anna   25
1      Bob   30
2  Charlie   35

In [ ]:
# создание DataFrame из массива NumPy
# Это стандарт для Machine Learning. Если у вас есть матрица чисел (например, картинка или признаки для нейросети), её легко превратить в DataFrame.

import numpy as np

# Создаем матрицу 3x2 (3 строки, 2 столбца)
arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

df = pd.DataFrame(arr, columns=['Feature_1', 'Feature_2'])
print(df)

   Feature_1  Feature_2
0         10         20
1         30         40
2         50         60

In [ ]:
df.shape # Размерность. Кортеж (количество строк, количество столбцов).

(3, 2)

In [ ]:
df.columns # получить список всех заголовков (Названия столбцов)

Index(['Feature_1', 'Feature_2'], dtype='object')

In [ ]:
df.index  # Показывает, как занумерованы строки. (Метки строк)

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.dtypes # Показывает Типы данных для каждого столбца

Feature_1    int64
Feature_2    int64
dtype: object

# Работа с CSV: нюансы read_csv

In [ ]:
# Если ваш файл идеально стандартизирован (разделитель — запятая, кодировка — UTF-8, есть заголовки), то загрузка выглядит так:
df = pd.read_csv('data.csv')

In [ ]:
df = pd.read_csv('data.csv', sep=';') # Если разделитель — точка с запятой

df = pd.read_csv('data.tsv', sep='\t') # Если разделитель — табуляция

In [ ]:
df = pd.read_csv('russian_data.csv', encoding='cp1251') # Для файлов из Windows на русском языке

df = pd.read_csv('legacy_data.csv', encoding='latin1') # Реже встречается (Западная Европа)

In [ ]:
df = pd.read_csv('no_header.csv', header=None) # Если В файле нет заголовков. Здесь колонки получат имена 0, 1, 2...

In [ ]:
# можете сразу при чтении переименовать столбцы.
my_cols = ['Date', 'Product', 'Price']
df = pd.read_csv('data.csv', header=0, names=my_cols)

# header=0 говорит: «Выкинь исходную первую строку (старый заголовок)».
#names=... говорит: «Используй вот эти новые имена».

In [ ]:
# Часто в файле первый столбец — это не данные, а идентификатор (ID) или дата, которую мы хотим использовать как индекс DataFrame.
# По умолчанию pandas создаст новый индекс 0, 1, 2..., а ваш ID сделает обычной колонкой.

df = pd.read_csv('data.csv', index_col=0) # Сделать первую колонку (0-ю по счету) индексом

df = pd.read_csv('data.csv', index_col='transaction_id') # Или по названию

# Чтение Excel файлов (read_excel)

In [ ]:
df = pd.read_excel('report.xlsx') # По умолчанию читает ПЕРВЫЙ лист файла

In [ ]:
df = pd.read_excel('report.xlsx', sheet_name='Sales_2024') # читает лист соответствующий по названию

df = pd.read_excel('report.xlsx', sheet_name=1)  # читает лист соответствующий по порядковому номеру

In [ ]:
# Прочитать ВСЕ листы сразу
# Если указать None, pandas вернет не DataFrame, а словарь (dict), где ключи — названия листов, а значения — датафреймы.

all_sheets = pd.read_excel('report.xlsx', sheet_name=None)
df_sales = all_sheets['Sales_2024'] # Доступ к конкретному листу из словаря

In [ ]:
df = pd.read_excel('report.xlsx', usecols="A,C,E:H") # Читаем только колонки A, C и диапазон от E до H

In [ ]:
df = pd.read_excel('report.xlsx', skiprows=3) # Пропустить первые 3 строки и начать читать с 4-й

In [ ]:
# Параметр converters позволяет принудительно задать тип данных для конкретного столбца в момент чтения.
df = pd.read_excel('stock.xlsx', converters={'Article_ID': str}) # Гарантируем, что артикул будет считан как строка (сохранит нули)

# Другие форматы: JSON, SQL, Parquet

In [ ]:
df = pd.read_json('data.json') # Чтение JSON файла

# JSON может быть записан по-разному: как список записей, как словарь столбцов и т.д. Если pandas выдает ошибку или странную таблицу, попробуйте поменять параметр orient.
# orient='records' — самый частый формат (список словарей: [{col:val}, {col:val}]).
# orient='split' — разделяет данные, индексы и колонки.

In [ ]:
# Чтение SQL-запросы
import pandas as pd
from sqlalchemy import create_engine # Библиотека SQLAlchemy создает соединение

# 1. Создаем подключение (движок)
engine = create_engine('postgresql://user:password@localhost:5432/mydatabase')

# 2. Пишем SQL запрос
query = "SELECT * FROM users WHERE age > 25"

# 3. Получаем DataFrame
df = pd.read_sql(query, engine)

In [ ]:
# Чтение Parquet (Паркет)
# Что это: Бинарный, колоночный формат хранения данных. Это стандарт в экосистеме Big Data (Hadoop, Spark).

Вам понадобится библиотека pyarrow или fastparquet.

# Чтение невероятно быстрое
df = pd.read_parquet('big_data.parquet')

# Сохранение (чтобы сэкономить место на диске)
df.to_parquet('compressed_data.parquet')

df = pd.read_parquet(
    'data/large_dataset.parquet',
    engine='pyarrow',
    columns=['user_id', 'timestamp', 'value'],
    use_nullable_dtypes=True
)

In [ ]:
# Pandas может извлекать таблицы из HTML-страниц

url = 'http://example.com/page_with_table.html'
tables = pd.read_html(url)

# tables – это список DataFrame, соответствующих всем найденным таблицам
df = tables[0]  # берем первую таблицу

# Экспорт данных в CSV, Excel, JSON, SQL

In [ ]:
# Экспорт в CSV
import pandas as pd

# Создаем пример DataFrame
data = {
    'Имя': ['Никита', 'Лиза', 'Степа', 'Егор'],
    'Возраст': [23, 22, 19, 26],
    'Город': ['Мадрид', 'Мадрид', 'Москва', 'Питер']
}

df = pd.DataFrame(data)

# Экспортируем DataFrame в CSV файл
df.to_csv('output.csv', index=False, encoding='utf-8')

In [ ]:
# Экспорт в Excel. Для работы с этим форматом необходимо установить библиотеку openpyxl.

# pip install openpyxl
# Экспортируем DataFrame в Excel файл
df.to_excel('output.xlsx', index=False, engine='openpyxl')

In [ ]:
# Экспорт в JSON

# Экспортируем DataFrame в JSON файл
df.to_json('output.json', orient='records', lines=True, force_ascii=False)

In [ ]:
# Экспорт в SQL
from sqlalchemy import create_engine

# Создаем соединение с базой данных
engine = create_engine('sqlite:///database.db')

# Экспортируем DataFrame в таблицу SQL
df.to_sql('таблица_данных', con=engine, index=False, if_exists='replace')

# Основные методы DF

In [ ]:
df.head() # По умолчанию: показывает 5 первых строк. При необходимости сколько строк выводить задаем в скобках

,Name,Gender,Age,Salary,Occupation,Start_Date,Hours_per_week,Age_category,Occupation_short
0,John Smith,Male,34,5000,Data Analyst,2018-04-23,40,Middle-aged,DA
1,Anna Brown,Female,29,5200,Software Dev,2019-08-15,45,Young,SD
2,Mark Lee,Male,41,4800,Project Manager,2016-03-12,38,Senior,PM
3,Lucy Hill,Female,36,5500,Data Scientist,2020-01-10,42,Middle-aged,DS
4,Alan Reed,Male,31,4600,HR Specialist,2021-06-07,40,Middle-aged,HR

In [ ]:
df.tail()   # 5 последних строк
df.tail(3)  # 3 последние строки

,Name,Gender,Age,Salary,Occupation,Start_Date,Hours_per_week,Age_category,Occupation_short
46,Sophia Harris,Female,36,5100,Data Scientist,2020-02-21,43,Middle-aged,DS
47,Liam Baker,Male,38,4900,Business Analyst,2016-07-29,35,Middle-aged,BA
48,Ava Thompson,Female,31,5300,Software Dev,2021-04-18,44,Middle-aged,SD

In [ ]:
df.sample()     # 1 случайная строка
df.sample(5)    # 5 случайных строк

# random_state: «Зерно» случайности.
df.sample(n=5, random_state=42) # при каждом запуске программы вы будете получать одни и те же «случайные» строки. Это важно для воспроизводимости экспериментов.

,Name,Gender,Age,Salary,Occupation,Start_Date,Hours_per_week,Age_category,Occupation_short
13,Olivia Lewis,Female,44,6100,CTO,2013-06-01,49,Senior,NaN
45,Oliver Roberts,Male,40,5400,Project Manager,2015-01-17,39,Senior,PM
47,Liam Baker,Male,38,4900,Business Analyst,2016-07-29,35,Middle-aged,BA
44,Emma Young,Female,33,5000,Business Analyst,2016-11-25,36,Middle-aged,BA
17,Amelia Scott,Female,40,5600,Data Scientist,2015-10-17,42,Senior,DS

In [ ]:
df.info() #  рентген таблицы

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              49 non-null     object
 1   Gender            49 non-null     object
 2   Age               49 non-null     int64
 3   Salary            49 non-null     int64
 4   Occupation        49 non-null     object
 5   Start_Date        49 non-null     object
 6   Hours_per_week    49 non-null     int64
 7   Age_category      49 non-null     object
 8   Occupation_short  43 non-null     object
dtypes: int64(3), object(6)
memory usage: 3.6+ KB

In [ ]:
df.describe() # быстрая статистика

             Age       Salary  Hours_per_week
count  49.000000    49.000000        49.00000
mean   35.183673  5193.877551        41.44898
std     5.325542   502.248346         4.34483
min    27.000000  4400.000000        35.00000
25%    31.000000  4800.000000        38.00000
50%    35.000000  5100.000000        41.00000
75%    39.000000  5500.000000        44.00000
max    46.000000  6300.000000        52.00000

In [ ]:
# Транспонирование быстрой статистики, когда колонок слишком много
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,49.0,35.183673,5.325542,27.0,31.0,35.0,39.0,46.0
Salary,49.0,5193.877551,502.248346,4400.0,4800.0,5100.0,5500.0,6300.0
Hours_per_week,49.0,41.448980,4.344830,35.0,38.0,41.0,44.0,52.0

In [ ]:
# Доступ к столбцам: Точка vs Скобки
df = pd.DataFrame({
    'City': ['Moscow', 'London', 'Paris'],
    'Population': [12000, 8500, 2200]
})

# Получаем столбец City
cities = df['City'] # через Квадратные скобки []

cities2 = df.City # Точечная нотация. (Атрибутивный доступ)
# Не работает, когда пробелы в названии
# Возможен конфликт имен с зарезервированными словами
# Не возможно создание новой колонки

## `loc[] `
Атрибут .loc (от слова Location) используется для доступа к данным по их МЕТКАМ (Labels).
Порядок: [строка, столбец]\

In [ ]:
from operator import index
import pandas as pd

data = {
    'Country': ['Russia', 'France', 'Italy', 'Germany'],
    'Capital': ['Moscow', 'Paris', 'Rome', 'Berlin'],
    'Population': [144, 67, 60, 83]
}

# Делаем страну индексом!
df = pd.DataFrame(data, index=data['Country'])
df = df[['Capital','Population']]
# (теперь строки называются 'Russia', 'France'...)

In [ ]:
# Если мы передадим в .loc[] только один аргумент, pandas поймет, что мы ищем строку.
df.loc[['France','Russia']]

       Capital  Population
France   Paris          67
Russia  Moscow         144

In [ ]:
# получить значение в конкретной ячейке или Можно брать подмножества (срез таблицы):

df.loc[['Russia', 'Germany'], 'Capital']

Russia     Moscow
Germany    Berlin
Name: Capital, dtype: object

In [ ]:
df.loc['France':'Germany'] # Срезы в .loc ВКЛЮЧАЮТ оба конца (Inclusive).

        Capital  Population
France    Paris          67
Italy      Rome          60
Germany  Berlin          83

In [ ]:
df.loc[df['Population'] > 80] # В .loc можно передавать не только конкретные имена, но и условия

        Capital  Population
Russia   Moscow         144
Germany  Berlin          83

## `.iloc[] `
Атрибут .iloc[] (от слова Integer Location) используется для доступа к данным исключительно по их численной позиции.\
df.iloc[номер_строки, номер_столбца]

In [ ]:
df.iloc[0:3,0:2] # В .iloc срезы работают как в обычных списках Python: Старт — включается. Конец (Stop) — НЕ включается (Exclusive).

       Capital  Population
Russia  Moscow         144
France   Paris          67
Italy     Rome          60

In [ ]:
df.iloc[[0, 3], [1]] # можете передать конкретный набор номеров, которые вам нужны.

         Population
Russia          144
Germany          83

In [ ]:
# Отрицательная индексация
df.iloc[-1] # Последняя строка таблицы
df.iloc[:, -1] # Все строки, но только последний столбец

Russia     144
France      67
Italy       60
Germany     83
Name: Population, dtype: int64

## Отбор строк по условию

In [ ]:
df[(df['Population'] > 80) & (df['Capital']=='Moscow')] # отобрать строки по условию

# Логика Python Pandas Описание
# И (Оба условия верны) and & Амперсанд
# ИЛИ (Хотя бы одно верно) or | Разделитель
# НЕ (Инверсия) not ~ Тильда\

       Capital  Population
Russia  Moscow         144

In [ ]:
df[df['Capital'].isin(['Moscow','Rome'])] # Метод .isin() Множественный выбор, аналог SQL-оператора IN (...).

       Capital  Population
Russia  Moscow         144
Italy     Rome          60

In [ ]:
# А если нужно выбрать всех, кто НЕ живет в этих городах? Просто поставьте ~ перед условием.
df[~df['Capital'].isin(['Moscow','Rome'])]

        Capital  Population
France    Paris          67
Germany  Berlin          83

In [ ]:
# Метод .between() (Диапазон) проверяет попадание в интервал.
df[df['Population'].between(60, 100)]
# По умолчанию .between включает границы (inclusive).
# Если нужно строгое неравенство, используйте параметр inclusive='neither'

        Capital  Population
France    Paris          67
Italy      Rome          60
Germany  Berlin          83

In [ ]:
# Метод .query() (SQL-стиль). Метод позволяет писать условия одной строкой внутри кавычек.

df.query("Population > 80 and Capital=='Moscow'")

       Capital  Population
Russia  Moscow         144

In [ ]:
# Самый крутой трюк .query() — это возможность ссылаться на внешние переменные Python.
# Для этого перед именем переменной ставится собачка @.

min_pop = 18
target_city = 'Moscow'

# Pandas поймет, что @min_age — это переменная из вашего кода, а Age — колонка
df.query("Population > @min_pop and Capital == @target_city")

       Capital  Population
Russia  Moscow         144

## Создание новых столбцов

In [ ]:
# Создаем столбец с одним и тем же значением для всего столбца
df['Status'] = 'Paid'
df['Population_new'] = 70
df

        Capital  Population Status  Population_new
Russia   Moscow         144   Paid              70
France    Paris          67   Paid              70
Italy      Rome          60   Paid              70
Germany  Berlin          83   Paid              70

In [ ]:
# Математика между столбцами (Векторизация)
df['Population_dif'] = df['Population_new'] - df['Population']
df

        Capital  Population Status  Population_new  Population_dif
Russia   Moscow         144   Paid              70             -74
France    Paris          67   Paid              70               3
Italy      Rome          60   Paid              70              10
Germany  Berlin          83   Paid              70             -13

In [ ]:
# Работа со строками (Конкатенация текста), Склеиваем текст
df['Full_Name'] = df['Capital'] + ' ' + df['Status']
df

,Capital,Population,Status,Population_new,Population_dif,Full_Name
Russia,Moscow,144,Paid,70,-74,Moscow Paid
France,Paris,67,Paid,70,3,Paris Paid
Italy,Rome,60,Paid,70,10,Rome Paid
Germany,Berlin,83,Paid,70,-13,Berlin Paid

In [ ]:
# Создаем столбец-флаг: True, если Population_dif выше 0, иначе False
df['Is_Expensive'] = df['Population_dif'] > 0
df

,Capital,Population,Status,Population_new,Population_dif,Full_Name,Is_Expensive
Russia,Moscow,144,Paid,70,-74,Moscow Paid,False
France,Paris,67,Paid,70,3,Paris Paid,True
Italy,Rome,60,Paid,70,10,Rome Paid,True
Germany,Berlin,83,Paid,70,-13,Berlin Paid,False

In [ ]:
# Переименование столбцов: метод .rename()
#В него нужно передать словарь, где ключи — это старые названия, а значения — новые.
import pandas as pd

df = pd.DataFrame({
    'First Name': ['Ivan', 'Anna'],
    'Age (years)': [25, 30]
})

# Создаем словарь переименований
new_names = {
    'First Name': 'first_name',
    'Age (years)': 'age'
}

# Применяем переименование. Перезаписав переменную df
df = df.rename(columns=new_names)

#df.rename(columns=new_names, inplace=True) # или используем параметр inplace

df

  first_name  age
0       Ivan   25
1       Anna   30

In [ ]:
# Изменение типов данных: метод .astype()
df = pd.DataFrame({
    'user_id': [1, 2, 3],
    'price': ['100', '250', '500'], # Это строки!
    'is_active': [0, 1, 1]          # Это целые числа (0 и 1)
})

print(df.dtypes)
# price        object
# is_active     int64

# Перезаписываем колонку 'price' её же измененной версией
df['price'] = df['price'].astype(int)

# То же самое с 'is_active'
df['is_active'] = df['is_active'].astype(bool)

print(df.dtypes)
# price        int32 (или int64)
# is_active     bool

user_id       int64
price        object
is_active     int64
dtype: object
user_id      int64
price        int64
is_active     bool
dtype: object

## Удаление строк и столбцов (метод drop)

In [ ]:
df

   user_id  price  is_active
0        1    100      False
1        2    250       True
2        3    500       True

In [ ]:
df_clean = df.drop(columns=['Is_Expensive','Full_Name']) # Удаление столбцов Через параметр columns
df_clean

KeyError: "['Is_Expensive', 'Full_Name'] not found in axis"

In [ ]:
# Удаление столбцов Через параметр axis
# Указываем названия и говорим, что искать их нужно по оси 1 (столбцы)
df_clean = df.drop(['Is_Expensive','Full_Name'], axis=1)
df_clean

In [ ]:
#Если нужно удалить конкретные строки по их индексу (метке), метод .drop() сделает это по умолчанию,
# так как ось строк (axis=0) стоит у него изначально.
df_clean = df.drop(['Germany'])
df_clean

In [ ]:
# Использование inplace=True Этот параметр приказывает Pandas: "Не создавай копию, сожги эти данные прямо в исходной таблице".
df.drop(columns=['Status'], inplace=True)

In [ ]:
# Ошибки не будет, даже если колонки 'Fake_Column' не существует
df = df.drop(columns=['Fake_Column'], errors='ignore')

In [ ]:
# удаление дублирующихся строк drop_duplicates()

df.drop_duplicates(
    subset=None, # список столбцов, по которым проверять дубликаты. Если не указан, проверяются все столбцы.
    keep='first', # определяет, какую из дублирующихся строк оставить: 'first' (по умолчанию) ,'last', False - удалить все дубликаты (оставить только строки, которые не повторяются)
    inplace=False, # если True, изменяет исходный DataFrame и возвращает None. Если False (по умолчанию), возвращает новый DataFrame.
    ignore_index=False # если True (доступно с Pandas 1.0), сбрасывает индексы после удаления дубликатов (индексы будут 0, 1, 2, ...)
)

## Обнаружение пропусков: isna() и isnull()

In [ ]:
import pandas as pd
import numpy as np

# Создаем таблицу с дырками (np.nan - это специальный объект "пустоты")
df = pd.DataFrame({
    'Name': ['Anna', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 35],       # У Боба нет возраста
    'City': ['Moscow', 'Paris', None] # У Чарли нет города
})

print(df.isna()) # вернет нам таблицу точно такого же размера, но состоящую только из True и False.
# True — значение пропущено (ячейка пустая).
# False — значение есть (всё в порядке).

In [ ]:
# никогда не используют df.isna() в чистом виде. Его всегда комбинируют с методом подсчета суммы — .sum().
# В Python логическое True равно 1, а False равно 0. Если мы просуммируем маску по столбцам, то получим точное количество пропусков в каждой колонке!
print(df.isna().sum())

In [ ]:
# Чтобы посмотреть не количество, а долю пропусков, вместо суммы (sum) используйте среднее значение (mean):
print(df.isna().mean() * 100)

In [ ]:
# Выведи мне только те строки, где колонка Age имеет пропуск (True)
missing_age_users = df[df['Age'].isna()]

print(missing_age_users)

In [ ]:
#А как найти тех, у кого возраст УКАЗАН? Для этого нужно инвертировать условие с помощью оператора тильда ~ (НЕ), или использовать метод-антоним .notna():

# Вариант 1 (через тильду)
good_users = df[~df['Age'].isna()]

# Вариант 2 (через notna)
good_users = df[df['Age'].notna()]

## Стратегия удаления: метод dropna()

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Anna', 'Bob', 'Charlie', 'David', np.nan],
    'Age': [25, np.nan, 35, 40, np.nan],
    'Email': ['a@a.ru', 'b@b.ru', np.nan, 'd@d.ru', np.nan]
})
df

In [ ]:
clean_df = df.dropna() # без параметров, он удалит ЛЮБУЮ строку, в которой есть хотя бы один пропуск (NaN)
clean_df

In [ ]:
# Удалим только полностью пустую строку (индекс 4)
df_all = df.dropna(how='all')
df_all

In [ ]:
# Удаляем строки только если пропуск находится в колонке 'Email'
df_subset = df.dropna(subset=['Email'])
df_subset

In [ ]:
# Удалит ВСЕ столбцы, в которых есть хотя бы один NaN
df_cols = df.dropna(axis=1)

In [ ]:
# оставит только те столбцы, в которых есть как минимум 1000 непустых (живых) значений
df.dropna(axis=1, thresh=1000)

## Стратегия заполнения: fillna() и interpolate()

In [ ]:
# Метод .fillna() позволяет заменить все пустоты (NaN) на какое-то конкретное значение.
# Заменяем пустоты в городе на слово 'Unknown' (Неизвестно)
df['City'] = df['City'].fillna('Unknown')

In [ ]:
# Метод соседнего значения (ffill и bfill)
df['Temp'].ffill() #(Forward Fill) — берет предыдущее непустое значение и "тянет" его вниз.
df['Temp']..bfill() #(Backward Fill) — берет следующее значение и "тянет" его вверх.

In [ ]:
# Умное заполнение: метод .interpolate()
# (интерполяция) проводит математическую линию между двумя известными точками
# и равномерно заполняет пустоты между ними.

# Вернем оригинальные данные с пропусками температуры:
# [15.0, NaN, NaN, 21.0]

df['Temp'] = df['Temp'].interpolate()
print(df['Temp']) # [ 15.0, 17.0, 19.0, 21.0]

## Сортировка по индексу (sort_index)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['IT', 'Sales', 'IT', 'HR', 'Sales'],
    'Salary': [120000, 80000, 150000, 70000, 95000],
    'Age': [28, 35, 25, 42, 30]
})

In [ ]:
df.sort_index() # сортировка строк по возрастанию. вместе с индексом перемещаются и значения

In [ ]:
df.sort_index(ascending=False) # сортировка строк по убыванию

In [ ]:
df.sort_index(axis=1) # Сортируем названия колонок по алфавиту

In [ ]:
df.sort_index(inplace=True) #Чтобы изменения вступили в силу используйте параметр inplace=True

## Сортировка по значениям (sort_values)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['IT', 'Sales', 'IT', 'HR', 'Sales'],
    'Salary': [120000, 80000, 150000, 70000, 95000],
    'Age': [28, 35, 25, 42, 30]
})

In [ ]:
df.sort_values(by='Salary') # Сортируем по значениям столбца Salary, по возрастанию

In [ ]:
df.sort_values(by='Salary', ascending=False) # Сортируем по значениям столбца Salary, по убыванию

In [ ]:
# Сортировка сразу по нескольким столбцам
# Department - по возрастанию (True), Salary - по убыванию (False)
df_pro = df.sort_values(
    by=['Department', 'Salary'],
    ascending=[True, False]
)

df_pro

In [ ]:
# pandas по умолчанию всегда будет отправлять пустые ячейки (NaN) в самый конец таблицы
# Пустые значения окажутся первыми
df.sort_values(by='Salary', na_position='first')

## Ранжирование данных (метод rank)

In [ ]:
# Метод .rank() возвращает новую колонку с "местами" (рангами), не меняя исходный порядок строк.

import pandas as pd

df = pd.DataFrame({
    'Name': ['Anna', 'Bob', 'Charlie', 'David'],
    'Score': [100, 90, 90, 80]
})

# Считаем ранг (по умолчанию от меньшего к большему)
# method='average' (можно не писать) для одинаковых значений берет средний ранг
df['Rank_Asc'] = df['Score'].rank()

print(df)

In [ ]:
# 1-е место тому, у кого больше баллов
df['Rank_Desc'] = df['Score'].rank(ascending=False)
df

In [ ]:
# Всем, кто разделил место, дается наилучший (минимальный) ранг
df['rank_min'] = df['Score'].rank(ascending=False, method='min')
df

In [ ]:
# Похож на спортивный, но места не "сгорают". Боб и Чарли получают 2-е место, а идущий за ними Дэвид получает 3-е место. В рейтинге не возникает дыр.
df['rank_dense'] = df['Score'].rank(ascending=False, method='dense')
df

In [ ]:
# Ничьих не бывает. Кто физически находится выше в таблице, тот и получает лучшее место.
#Боб записан раньше Чарли, поэтому Боб получает 2-е место, а Чарли — 3-е.
df['rank_first'] = df['Score'].rank(ascending=False, method='first')
df

In [ ]:
# пропуски NaN не будет ранжировать — в колонке с рангом тоже появится NaN.

# отправить таких людей в самый конец рейтинга - используйте параметр na_option='bottom'.

# отправить их на 1-е место — используйте na_option='top'.

## Метод .groupby() Механика Split-Apply-Combine (Разделение-Применение-Объединение).

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'Sales', 'IT', 'HR', 'Sales'],
    'Employee': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Salary': [120000, 80000, 150000, 70000, 95000]
})

In [ ]:
# Синтаксис: таблица.groupby(колонка_для_группировки)[колонка_для_расчета].функция()
df.groupby('Department')['Salary'].mean()

In [ ]:
# Группировка без выбора столбца
# Вычисляем среднее для всех возможных колонок
# (в новых версиях pandas нужно добавить numeric_only=True, чтобы он не пытался усреднять текст)
df.groupby('Department').mean(numeric_only=True)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Moscow', 'Moscow', 'Kazan', 'Kazan', 'Moscow', 'Kazan'],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'Sales': [1000, 500, 800, 300, 1200, 400],
    'Profit': [200, 50, 150, 30, 250, 40]
})

# Группируем по нескольким полям с разу, списку ['City', 'Category']
# по умолчанию столбцы группироки станут индексом MultiIndex
df.groupby(['City', 'Category'])['Sales'].sum()

In [ ]:
df.groupby(['City', 'Category'], as_index=False)['Sales'].sum()
# Чтобы pandas не превращал колонки, по которым мы группируем, в индексы,
# а оставил их обычными столбцами, нужно передать в .groupby() магический параметр as_index=False.

## Итерирование по группам и метод get_group()

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Moscow', 'Kazan', 'Moscow', 'Sochi', 'Kazan'],
    'Name': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Sales': [100, 200, 150, 300, 250]
})

# Создаем объект GroupBy
grouped = df.groupby('City')
grouped

In [ ]:
# Перебираем все группы
for city_name, group_df in grouped:
    print(f"=== Город: {city_name} ===")
    print(group_df)
    print("\n") # Отступ для красоты

In [ ]:
# Вытаскиваем датафрейм только для Москвы
moscow_df = grouped.get_group('Moscow')
moscow_df

In [ ]:
# Извлекаем Electronics в Москве
df.groupby(['City', 'Category']).get_group(('Moscow', 'Electronics'))

## Базовые функции: sum(), mean(), count(), median()

In [ ]:
df.groupby('City', as_index=False)['Sales'].sum() # сумма значений.

df.groupby('City', as_index=False)['Sales'].mean() # среднее (боится аномально больших/маленьких значений).

df.groupby('City', as_index=False)['Sales'].median() # середина данных (не боится выбросов, "честное" среднее).

df.groupby('City', as_index=False)['Sales'].count() # количество элементов, исключая NaN.

df.groupby('City', as_index=False)['Sales'].size() # физическое количество строк.

## Множественная агрегация с методом .agg()

In [ ]:
# Метод .agg() позволяет применить сразу несколько математических функций за один проход.
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'Sales', 'Sales', 'HR'],
    'Name': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Salary': [120000, 80000, 90000, 110000, 70000],
    'Age': [25, 30, 35, 40, 28]
})

# Смотрим статистику зарплат по каждому отделу
salary_stats = df.groupby('Department')['Salary'].agg(['min', 'max', 'mean'])

print(salary_stats)

In [ ]:
# Разные функции к разным столбцам.
# в .agg() нужно передать словарь dict.
# Ключи словаря — это названия колонок.
# Значения — это функции (или списки функций), которые к ним нужно применить.

# Для возраста считаем среднее, для зарплаты - сумму, для имени - количество
complex_stats = df.groupby('Department').agg({
    'Age': 'mean',
    'Salary': 'sum',
    'Name': 'count'
})

print(complex_stats)

In [ ]:
# Идеальная сводная таблица с понятными именами
perfect_stats = df.groupby('Department', as_index=False).agg(
    avg_age=('Age', 'mean'),           # Новая колонка avg_age
    total_budget=('Salary', 'sum'),    # Новая колонка total_budget
    employee_count=('Name', 'count')   # Новая колонка employee_count
)

print(perfect_stats)

In [ ]:
# Настраиваемые функции агрегации (lambda)

df.groupby('Department')['Salary'].agg(lambda x: x.max() - x.min())

In [ ]:
# посчитаем среднюю зарплату по отделу, а также соберем имена всех сотрудников этого отдела в одну строку через запятую.
# Для склеивания строк в Python используется метод ', '.join(список). Применим его через лямбду:

report = df.groupby('Department', as_index=False).agg(
    avg_salary=('Salary', 'mean'),
    # x - это Series с именами. Мы склеиваем их через запятую
    employees_list=('Name', lambda x: ', '.join(x))
)

print(report)

In [ ]:
# Например, мы хотим узнать, сколько сотрудников в каждом отделе получают зарплату строго больше 100 000.
rich_count = df.groupby('Department')['Salary'].agg(
    lambda x: (x > 100000).sum()
)

print(rich_count)

## Метод transform() для вещания результатов на весь DataFrame

In [ ]:
# можно сказать что это аналог оконной функции в sql
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'Sales', 'Sales', 'Sales'],
    'Name': ['Anna', 'Bob', 'Charlie', 'David', 'Eve'],
    'Salary': [120000, 80000, 50000, 90000, 100000]
})

# transform считает среднее по отделу и проставляет его каждому сотруднику этого отдела
df['Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')

print(df)

In [ ]:
# Делим личную Salary на сгруппированную и трансформированную сумму (бюджет отдела):
df['%_of_Budget'] = df['Salary'] / df.groupby('Department')['Salary'].transform('sum') * 100

print(df[['Name', 'Department', 'Salary', '%_of_Budget']])

## Метод filter() для отсеивания целых групп

In [ ]:
# Метод .filter() после .groupby() позволяет отфильтровать целые группы на основе заданного условия.
# Метод .filter() принимает на вход лямбда-функцию.
# Задача лямбда-функции — вернуть одно значение: True (оставить группу) или False (выбросить группу из итоговой таблицы).

import pandas as pd

df = pd.DataFrame({
    'Team': ['Red', 'Red', 'Red', 'Blue', 'Green', 'Green'],
    'Player': ['Anna', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Score': [10, 20, 15, 100, 30, 40]
})

# x - это DataFrame одной конкретной команды
# len(x) - количество строк в этом DataFrame
valid_teams = df.groupby('Team').filter(lambda x: len(x) >= 2)

print(valid_teams)

In [ ]:
# Оставляем команды, где средний Score больше 20
high_score_teams = df.groupby('Team').filter(lambda x: x['Score'].mean() > 20)

print(high_score_teams)

## Использование pd.concat для склейки df вдоль осей

In [ ]:
import pandas as pd

# Данные за январь
df_jan = pd.DataFrame({
    'user_id': [1, 2],
    'revenue': [100, 200]
})

# Данные за февраль
df_feb = pd.DataFrame({
    'user_id': [3, 4],
    'revenue': [300, 400]
})

# Вертикальная склейка или склейка вниз(axis=0)
# axis=0 можно не писать, это значение по умолчанию
df_total = pd.concat([df_jan, df_feb],ignore_index=True) # ignore_index=True Чтобы индексы пересчитались заново

print(df_total)

In [ ]:
# Таблица с именами
df_names = pd.DataFrame({
    'name': ['Anna', 'Bob', 'Charlie']
})

# Таблица с демографией
df_demo = pd.DataFrame({
    'age': [25, 30, 35],
    'city': ['Moscow', 'Kazan', 'Sochi']
})

# Горизонтальная склейка (axis=1)
# Склеиваем слева направо
df_full = pd.concat([df_names, df_demo], axis=1)

print(df_full)

In [ ]:
# Вертикальная склейка или склейка вниз(axis=0)
# и передача списка названий для наших исходных таблиц.
# получаем MultiIndex, который показывает происхождение данных.
df_total = pd.concat([df_jan, df_feb], keys=['jan', 'feb'])
print(df_total)

## Merge Типы соединений: Inner, Left, Right, Outer

In [ ]:
# Синтаксис
pd.merge(left, right, # DataFrame для объединения
         how='inner',
         on=None, # имя столбца(ов) для соединения (если названия одинаковые в обоих DataFrame).
         left_on=None, right_on=None, # имена столбцов в левом и правом DataFrame для соединения (если названия разные).
         left_index=False, right_index=False, # использовать ли индексы для соединения
         suffixes=('_x', '_y'), # суффиксы для столбцов с одинаковыми именами (по умолчанию ('_x', '_y'))
         indicator=False, # добавить столбец _merge с информацией о происхождении строки ('left_only', 'right_only', 'both').
         validate=None # проверка уникальности ключей: '1:1', '1:m', 'm:1', 'm:m')

In [ ]:
import pandas as pd

# Таблица 1 (Левая): Клиенты (ID 1, 2, 3)
df_users = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Anna', 'Bob', 'Charlie']
})

# Таблица 2 (Правая): Покупки (ID 1, 2, 4)
df_purchases = pd.DataFrame({
    'id': [1, 2, 4],
    'item': ['Apple', 'Banana', 'Orange']
})

In [ ]:
# Соединяем по колонке 'id'
df_inner = pd.merge(df_users, df_purchases, on='id', how='inner')
print(df_inner)

In [ ]:
# Главная таблица - левая (df_users)
df_left = pd.merge(df_users, df_purchases, on='id', how='left')
print(df_left)

In [ ]:
# Главная таблица - правая (df_purchases)
df_right = pd.merge(df_users, df_purchases, on='id', how='right')
print(df_right)

In [ ]:
# Сохраняем абсолютно все данные
df_outer = pd.merge(df_users, df_purchases, on='id', how='outer')
print(df_outer)

In [ ]:
# merge можно вызывать как метод самого датафрейма (кому как удобнее):
df_users.merge(df_purchases, on='id', how='left')

In [ ]:
# Параметр on используется только, когда названия колонок в левой и правой таблицах абсолютно идентичны.
# Если названия отличаются, то используются параметры left_on (ключ левой таблицы) и right_on (ключ правой таблицы).
import pandas as pd

# Левая таблица: Клиенты
df_clients = pd.DataFrame({
    'client_id': [1, 2, 3],
    'name': ['Anna', 'Bob', 'Charlie']
})

# Правая таблица: Заказы
df_orders = pd.DataFrame({
    'user_id': [2, 3, 4],
    'amount': [500, 1500, 300]
})

# Объединяем, указывая разные ключи
df_merged = pd.merge(
    df_clients,
    df_orders,
    left_on='client_id',
    right_on='user_id',
    how='inner'
)

print(df_merged)

In [ ]:
df_merged.drop(columns=['user_id']) # удаляем дублирование - лишний ключ

In [ ]:
# Слияние по нескольким ключам (Список)
df_employees = pd.DataFrame({
    'first_name': ['John', 'John', 'Jane'],
    'last_name': ['Doe', 'Smith', 'Doe'],
    'salary': [50000, 60000, 70000]
})

df_bonuses = pd.DataFrame({
    'first_name': ['John', 'Jane'],
    'last_name': ['Doe', 'Doe'],
    'bonus': [5000, 7000]
})

# Соединяем строго по совпадению Имени И Фамилии
df_full = pd.merge(
    df_employees,
    df_bonuses,
    on=['first_name', 'last_name'],
    how='left'
)

print(df_full)

In [ ]:
# Слияние по индексам Параметры left_index и right_index
import pandas as pd

# Левая таблица: Клиенты (ID спрятан в индексе!)
df_clients = pd.DataFrame({
    'name': ['Anna', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Правая таблица: Заказы (ID - это обычная колонка)
df_orders = pd.DataFrame({
    'user_id': [2, 3, 4],
    'amount': [500, 1500, 300]
}, index=[2, 3, 4])

# Левая таблица: ключ в индексе (left_index=True)
# Правая таблица: ключ в колонке (right_on='user_id')
df_mixed = pd.merge(
    df_clients,
    df_orders,
    left_index=True,
    right_on='user_id',
    how='inner'
)

print(df_mixed)

In [ ]:
# Соединяем две таблицы исключительно по их индексам.
# результат сохраняют индексы-ключи в качестве индексов новой таблицы.
df_idx_merge = pd.merge(
    df_clients,
    df_orders,
    left_index=True,
    right_index=True,
    how='outer'
)

print(df_idx_merge)

## Метод .join() — младший брат merge

In [ ]:
# По умолчанию .join() работает строго по индексам и делает левое соединение (how='left').

df_joined = df_clients.join(df_orders)
# Это абсолютно то же самое, что:
# pd.merge(df_clients, df_orders, left_index=True, right_index=True, how='left')

print(df_joined)

In [ ]:
# Синтаксис
DataFrame.join(
    other, # DF, который присоединяется к текущему.
    on=None, # столбец в левом DF, который будет использоваться как индекс для соединения (если other уже имеет нужный индекс).
    how='left',
    lsuffix='', # суффиксы для имён столбцов, если в обоих DataFrame есть столбцы с одинаковыми названиями.
    rsuffix='', # суффиксы для имён столбцов, если в обоих DataFrame есть столбцы с одинаковыми названиями.
    sort=False # (по умолчанию False) — сортировать ли результат по индексам.
)

# Строковые функции (.str)
## Изменение регистра и обрезка пробелов

In [ ]:
# Главное правило при работе с текстом в pandas:
# чтобы применить строковый метод к целой колонке, перед названием метода всегда нужно писать слово .str (от слова string — строка).

import pandas as pd

df = pd.DataFrame({
    'Name': [' aNNa ', 'BOB', 'charlie  '],
    'City': ['Moscow', ' moscow ', 'MOSCOW']
})

print(df)

        Name      City
0      aNNa     Moscow
1        BOB   moscow
2  charlie      MOSCOW

In [ ]:
df['Name_clean'] = df['Name'].str.title() # делает первую букву каждого слова заглавной

df['City_clean'] = df['City'].str.lower() # делает все буквы строчными (маленькими)

df['City_clean'] = df['City'].str.upper() # делает все буквы прописными (БОЛЬШИМИ)

df['Name_clean'] = df['Name'].str.capitalize() # делает заглавной только самую первую букву в строке, остальные опускает.

In [ ]:
# Обрезка невидимых пробелов (strip)

df['City_clean'] = df['City_clean'].str.strip() # удаляет пробелы с обоих концов строки
df['Name_clean'] = df['Name_clean'].str.lstrip() # удаляет пробелы только слева (Left)
df['Name_clean'] = df['Name_clean'].str.rstrip() # удаляет пробелы только справа (Right)

print(df['City_clean'].tolist())

['MOSCOW', 'MOSCOW', 'MOSCOW']

In [ ]:
# Метод цепочки (Chaining)
# Каждый новый строковый метод требует своего собственного .str!
# сразу делаем все буквы строчными и удаляем лишние пробелы
df['City_perfect'] = df['City'].str.lower().str.strip()

## Поиск подстрок и замена (contains, replace)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'profession': ['Data Scientist', 'data analyst', 'System Administrator', 'Senior Analyst'],
    'salary': ['$1000', '1200$', '1500 USD', '$2000']
})

df

             profession    salary
0        Data Scientist     $1000
1          data analyst     1200$
2  System Administrator  1500 USD
3        Senior Analyst     $2000

In [ ]:
# .str.contains('искомое_слово') возвращает колонку из True и False (булеву маску). True ставится там, где слово нашлось.
# Параметр case=False отключает чувствительность к регистру (найдет и analyst, и Analyst)
df['profession'].str.contains('analyst', case=False)

0    False
1     True
2    False
3     True
Name: profession, dtype: bool

In [ ]:
# Ищем слово Analyst.
# Параметр case=False отключает чувствительность к регистру (найдет и analyst, и Analyst)
mask = df['profession'].str.contains('analyst', case=False)

# Применяем маску к датафрейму
df_analysts = df[mask]

print(df_analysts)

       profession salary
1    data analyst  1200$
3  Senior Analyst  $2000

In [ ]:
# Замена текста: .str.replace()
# Цепочка замен: сначала $, потом ' USD'
df['salary_clean'] = df['salary'].str.replace('$', '').str.replace(' USD', '')

# Теперь это чистые цифры (хоть пока и в текстовом формате)
print(df['salary_clean'].tolist())

['1000', '1200', '1500', '2000']

In [ ]:
# Безопасная замена символа плюса. Добавляем regex=False чтобы не воспринимались регулярные выражения
df['grade'] = ['C++', 'Python','','']
df['grade_clean'] = df['grade'].str.replace('+', ' Plus', regex=False)
df['grade_clean']

0    C Plus Plus
1         Python
2
3
Name: grade_clean, dtype: object

## Разделение строк и извлечение данных

In [ ]:
# Разделение строки: .str.split() - возвращает колонку, где в каждой ячейке лежит список (list)
import pandas as pd

df = pd.DataFrame({
    'full_name': ['Anna Smith', 'Bob Johnson', 'Charlie Brown'],
    'badge_info': ['ID: 101 - Active', 'ID: 102 - Fired', 'ID: 103 - Active']
})

# Разрезаем по пробелу (' ')
names_split = df['full_name'].str.split(' ')

print(names_split)

0       [Anna, Smith]
1      [Bob, Johnson]
2    [Charlie, Brown]
Name: full_name, dtype: object

In [ ]:
# expand=True превращает списки в DataFrame из двух колонок
df[['first_name', 'last_name']] = df['full_name'].str.split(' ', expand=True)

print(df[['full_name', 'first_name', 'last_name']])

       full_name first_name last_name
0     Anna Smith       Anna     Smith
1    Bob Johnson        Bob   Johnson
2  Charlie Brown    Charlie     Brown

In [ ]:
# Извлечение данных: .str.extract() - работает на основе регулярных выражений (RegEx)
# \d+ — означает «найди одну или несколько цифр подряд».
# шаблон нужно обязательно обернуть в круглые скобки ()

# Шаблон r'(\d+)' означает: найди цифры и извлеки их
df['employee_id'] = df['badge_info'].str.extract(r'(\d+)')

print(df[['badge_info', 'employee_id']])

         badge_info employee_id
0  ID: 101 - Active         101
1   ID: 102 - Fired         102
2  ID: 103 - Active         103

## Преобразование в формат datetime (to_datetime)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'date_str': ['2023-01-15', '2023-02-20', '2023-03-05']
})

# Превращаем текст в настоящие даты
df['date_dt'] = pd.to_datetime(df['date_str'])

df.dtypes

date_str            object
date_dt     datetime64[ns]
dtype: object

In [ ]:
# добавляйте параметр dayfirst=True (день идет первым) всегда, когда работаете с европейскими (и российскими) выгрузками,

df_eu = pd.DataFrame({'date': ['10.01.2023', '12.05.2023']})

# Без dayfirst pandas решит, что это октябрь и декабрь
df_eu['wrong'] = pd.to_datetime(df_eu['date'])

# С dayfirst всё сработает корректно (январь и май)
df_eu['correct'] = pd.to_datetime(df_eu['date'], dayfirst=True)

df_eu

         date      wrong    correct
0  10.01.2023 2023-10-01 2023-01-10
1  12.05.2023 2023-12-05 2023-05-12

In [ ]:
# можно подсказать шаблон с помощью параметра format.
# Шаблон собирается из специальных кодов:
# %Y — Год из 4 цифр (2023)
# %m — Месяц из 2 цифр (01-12)
# %d — День из 2 цифр (01-31)

# Дата в формате "Год/День/Месяц"
df_hard = pd.DataFrame({'date': ['2023/15/01', '2023/20/02']})

# Явно указываем, где что лежит
df_hard['clean_date'] = pd.to_datetime(df_hard['date'], format='%Y/%d/%m')

print(df_hard['clean_date'].tolist())

[Timestamp('2023-01-15 00:00:00'), Timestamp('2023-02-20 00:00:00')]

In [ ]:
df_dirty = pd.DataFrame({
    'date': ['2023-01-01', 'Ошибочка', '2023-01-03']
})

# Игнорируем ошибки, превращая мусор в NaT (Not a Time) — это аналог NaN, но специально для временных колонок.
df_dirty['clean'] = pd.to_datetime(df_dirty['date'], errors='coerce')

print(df_dirty)

         date      clean
0  2023-01-01 2023-01-01
1    Ошибочка        NaT
2  2023-01-03 2023-01-03

## Аксессор .dt: извлечение года, месяца, дня недели

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'purchase_date': pd.to_datetime(['2023-01-15', '2023-05-20', '2024-12-31'])
})

print(df.dtypes)

purchase_date    datetime64[ns]
dtype: object

In [ ]:
# С помощью .dt мы можем извлечь любой компонент даты в отдельную колонку:
# .dt.year — год
# .dt.month — месяц (числом от 1 до 12)
# .dt.day — день (числом от 1 до 31)

# Разбираем дату на части
df['year'] = df['purchase_date'].dt.year
df['month'] = df['purchase_date'].dt.month
df['day'] = df['purchase_date'].dt.day

print(df)

  purchase_date  year  month  day
0    2023-01-15  2023      1   15
1    2023-05-20  2023      5   20
2    2024-12-31  2024     12   31

In [ ]:
# .dt.dayofweek (или .dt.weekday) — возвращает порядковый номер дня недели.
# Важно: отсчет начинается с нуля! 0 — это понедельник, 6 — это воскресенье.
df['weekday_num'] = df['purchase_date'].dt.dayofweek
df['weekday_num2'] = df['purchase_date'].dt.weekday

# .dt.day_name() — возвращает текстовое название дня недели по умолчанию на английском (Monday, Tuesday...)
df['weekday_name'] = df['purchase_date'].dt.day_name() # Параметр locale='ru_RU' - сработает только если русская локаль установлена в системе

print(df[['purchase_date', 'weekday_num', 'weekday_num2', 'weekday_name']])

  purchase_date  weekday_num  weekday_num2 weekday_name
0    2023-01-15            6             6       Sunday
1    2023-05-20            5             5     Saturday
2    2024-12-31            1             1      Tuesday

In [ ]:
# .dt.is_month_end — возвращает True, если это последний день месяца
df['is_end_of_month'] = df['purchase_date'].dt.is_month_end

# .dt.is_leap_year — возвращает True, если год високосный (366 дней).
df['leap_year'] = df['purchase_date'].dt.is_leap_year

# .dt.days_in_month — подскажет, сколько всего дней в месяце этой даты (28, 29, 30 или 31)
df['days_month'] = df['purchase_date'].dt.days_in_month

print(df[['purchase_date', 'is_end_of_month','leap_year','days_month']])

  purchase_date  is_end_of_month  leap_year  days_month
0    2023-01-15            False      False          31
1    2023-05-20            False      False          31
2    2024-12-31             True       True          31

## Основы ресемплирования (resample)

In [ ]:
# брат-близнец метода .groupby(), но созданный исключительно для времени.
# по умолчанию колонка с датами (формата datetime64) должна находиться в индексе датафрейма!

import pandas as pd

# Генерируем даты за 40 дней (начиная с 1 января 2023 года)
dates = pd.date_range(start='2023-01-01', periods=40, freq='D')

df = pd.DataFrame({
    'date': dates,
    'sales': [10] * 40  # Пусть каждый день продается ровно по 10 штук
})

# Правило №1: Переносим дату в индекс!
df = df.set_index('date')

print(df.head(3))

            sales
date
2023-01-01     10
2023-01-02     10
2023-01-03     10

In [ ]:
# 'W' (Weekly) — по неделям (конец недели по умолчанию — воскресенье).
# 'M' (Month End) — по месяцам (на последний день месяца).
# 'MS' (Month Start) — по месяцам (на первый день месяца).
# 'Y' или 'A' (Year End) — по годам.
# 'Q' (Quarter) — по кварталам.

# Суммарные продажи по неделям
weekly_sales = df.resample('W')['sales'].sum()
weekly_sales.head(3)

date
2023-01-01    10
2023-01-08    70
2023-01-15    70
Freq: W-SUN, Name: sales, dtype: int64

In [ ]:
# Суммарные продажи по месяцам (на конец месяца)
monthly_sales = df.resample('M')['sales'].sum()
monthly_sales

/tmp/ipykernel_12103/667992589.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales = df.resample('M')['sales'].sum()

date
2023-01-31    310
2023-02-28     90
Freq: ME, Name: sales, dtype: int64

In [ ]:
# Ресемплирование без переноса в индекс (Параметр on)

# Возвращаем плоскую таблицу (дата снова стала колонкой)
df_flat = df.reset_index()

# Ресемплируем по кварталам (Q), используя параметр on='date'
# Не забываем про as_index=False, как в groupby, чтобы таблица осталась плоской!
quarter_sales = df_flat.resample('Q', on='date').sum()

# Для плоских таблиц после resample нужно аккуратно сбросить индекс
print(quarter_sales.reset_index(drop=True))

/tmp/ipykernel_12103/22823196.py:8: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  quarter_sales = df_flat.resample('Q', on='date').sum()

   sales
0    400

# Создание базовых сводных таблиц через pivot()

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'city': ['Moscow', 'Kazan', 'Moscow', 'Kazan'],
    'temp': [-5, -10, -2, -8]
})

print(df)

         date    city  temp
0  2023-01-01  Moscow    -5
1  2023-01-01   Kazan   -10
2  2023-01-02  Moscow    -2
3  2023-01-02   Kazan    -8

In [ ]:
# Не работает с дубликатами, он умеет только переставлять ячейки местами. Он не умеет вычислять и агрегировать данные!

# index — какая колонка станет строками (пойдет сверху вниз).
# columns — какая колонка станет новыми заголовками столбцов (пойдет слева направо).
# values — значения из какой колонки заполнят ячейки на пересечении.

df_pivot = df.pivot(index='date', columns='city', values='temp')

print(df_pivot)

city        Kazan  Moscow
date
2023-01-01    -10      -5
2023-01-02     -8      -2

# Мощный метод pivot_table() (аналог сводных таблиц Excel)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-01', '2023-01-01', '2023-01-02'],
    'city': ['Moscow', 'Moscow', 'Kazan', 'Kazan'],
    'sales': [100, 250, 500, 300]
})

print(df)

         date    city  sales
0  2023-01-01  Moscow    100
1  2023-01-01  Moscow    250
2  2023-01-01   Kazan    500
3  2023-01-02   Kazan    300

In [ ]:
# Метод pivot_table() работает как гибрид изменения формы (.pivot()) и группировки (.groupby())

# Строим настоящую сводную таблицу
pivot_sum = pd.pivot_table(
    df,
    index='date',       # Строки (сверху вниз)
    columns='city',     # Столбцы (слева направо)
    values='sales',     # Что считаем
    aggfunc='sum',      # Как считаем (сумма)
    fill_value=0,       # Заменяем пустоты на нули
    margins=True      # Добавляем строку и столбец "Итого"

)

print(pivot_sum)

city        Kazan  Moscow   All
date
2023-01-01    500     350   850
2023-01-02    300       0   300
All           800     350  1150

# Распрямление данных с помощью melt()

In [ ]:
import pandas as pd

df_wide = pd.DataFrame({
    'Company': ['Apple', 'Google'],
    '2021': [100, 150],
    '2022': [200, 250],
    '2023': [300, 350]
})

print(df_wide)

  Company  2021  2022  2023
0   Apple   100   200   300
1  Google   150   250   350

In [ ]:
# Плавим таблицу (столбцы превращаются в строки), оставляя Company как якорь
# variable (переменная) — сюда упадут бывшие названия столбцов (наши года).
# value (значение) — сюда упадут цифры из ячеек.

df_long = pd.melt(df_wide,
                  id_vars='Company',    # По умолчанию melt плавит все колонки, которые не указаны в id_vars
                  var_name='Year',      # Так назовем колонку с годами
                  value_name='Revenue'  # Так назовем колонку с выручкой
                  )

# Отсортируем для красоты
print(df_long.sort_values('Company'))

  Company  Year  Revenue
0   Apple  2021      100
2   Apple  2022      200
4   Apple  2023      300
1  Google  2021      150
3  Google  2022      250
5  Google  2023      350

In [ ]:
# Выбор конкретных колонок для расплавления (value_vars)

df_messy = pd.DataFrame({
    'Company': ['Apple', 'Google'],
    'CEO': ['Tim Cook', 'Sundar Pichai'], # Эта колонка нам не нужна
    '2022': [200, 250],
    '2023': [300, 350]
})

# Плавим только 2022 и 2023 года, колонку CEO игнорируем
df_selected = pd.melt(
    df_messy,
    id_vars='Company',
    value_vars=['2022', '2023'],  # Явно указываем, что плавить
    var_name='Year',
    value_name='Revenue'
)

print(df_selected.head(2))
# Результат: CEO исчез, таблица аккуратно расплавилась

  Company  Year  Revenue
0   Apple  2022      200
1  Google  2022      250

# Понятие уровней индекса

In [ ]:
# Создание мультииндекса через set_index()
import pandas as pd

# Обычная "плоская" таблица
df = pd.DataFrame({
    'Country': ['Russia', 'Russia', 'Belarus', 'Belarus'],
    'City': ['Moscow', 'Kazan', 'Minsk', 'Gomel'],
    'Sales': [1000, 500, 800, 300]
})

# Переносим ДВЕ колонки в индекс
df_multi = df.set_index(['Country', 'City'])
# Уровень 0 (level=0) — это Country (самый внешний, старший уровень).
# Уровень 1 (level=1) — это City (внутренний, младший уровень).

# мультииндекс хранится как список кортежей (tuples).

print(df_multi)

                Sales
Country City
Russia  Moscow   1000
        Kazan     500
Belarus Minsk     800
        Gomel     300

In [ ]:
import pandas as pd

# Создаем плоскую таблицу и сразу делаем из нее MultiIndex
df = pd.DataFrame({
    'Year': [2022, 2022, 2023, 2023],
    'Quarter': ['Q1', 'Q2', 'Q1', 'Q2'],
    'Revenue': [100, 150, 200, 250]
}).set_index(['Year', 'Quarter'])

print(df)

              Revenue
Year Quarter
2022 Q1           100
     Q2           150
2023 Q1           200
     Q2           250

In [ ]:
# Выбор по внешнему уровню (Уровень 0)

# С самым левым (внешним) уровнем работать проще всего.
# Метод .loc[] по умолчанию обращается именно к нему
df_2022 = df.loc[2022]

print(df_2022) # теперь внешним индексом стали кварталы

         Revenue
Quarter
Q1           100
Q2           150

In [ ]:
# Точечный выбор: Кортежи (Tuples)
#  Чтобы передать составной адрес для одной строки в MultiIndex, мы обязаны обернуть его в круглые скобки (кортеж).

# Передаем кортеж (Уровень_0, Уровень_1)
q1_2023 = df.loc[(2023, 'Q1')]

print(q1_2023)

Revenue    200
Name: (2023, Q1), dtype: int64

In [ ]:
# Выбор по внутреннему уровню (Метод xs)
# Для "пробивания" индекса насквозь и поиска по любому внутреннему уровню используется  метод .xs() (от слова cross-section — поперечный срез).

# передаем в него два параметра: что ищем и на каком уровне.
# Ищем 'Q1' на уровне с именем 'Quarter' (или level=1)
df_all_q1 = df.xs('Q1', level='Quarter')

print(df_all_q1)

      Revenue
Year
2022      100
2023      200

## Методы stack() и unstack()

In [ ]:
import pandas as pd

df = pd.DataFrame({
    '2022': [100, 200],
    '2023': [150, 250]
}, index=['Moscow', 'Kazan'])

df.index.name = 'City'

df

        2022  2023
City
Moscow   100   150
Kazan    200   250

In [ ]:
# Этот метод берет все названия колонок и переносит их в индекс строк,
# создавая новый, самый глубокий (внутренний) уровень мультииндекса.
# Загибаем колонки (года) в строки
df_stacked = df.stack()

df_stacked

City
Moscow  2022    100
        2023    150
Kazan   2022    200
        2023    250
dtype: int64

In [ ]:
# Метод .unstack() делает ровно обратное.
# Он берет самый внутренний уровень индекса строк (по умолчанию) и "разворачивает" его, превращая в новые колонки

# Разворачиваем самый внутренний индекс (года) обратно в колонки
df_unstacked = df_stacked.unstack()

df_unstacked

        2022  2023
City
Moscow   100   150
Kazan    200   250

In [ ]:
# Но мы можем передать ему индекс любого другого уровня или его имя!
# Превращаем в колонки нулевой уровень (города)
df_city_columns = df_stacked.unstack(level='City') # аналогично level=0

df_city_columns

City  Moscow  Kazan
2022     100    200
2023     150    250

# Трансформация данных (доп. из другого курса)

### apply()

Функция __apply()__ используется для более сложных трансформаций, в которых требуется применить функцию ко всему массиву данных. В качестве аргумента этого метода выступает функция (неважно, лямбда-функция или нет)

In [ ]:
df = pd.read_csv('https://drive.google.com/uc?export=download&id=1J1edk5yMt8tkFe7prA46mmCG5B6ORSLk')

In [ ]:
def age_category(age):
    if age < 30:
        return 'Young'
    elif 30 <= age < 40:
        return 'Middle-aged'
    else:
        return 'Senior'

df['Age_category'] = df['Age'].apply(age_category)

In [ ]:
# Тот же самый результат, но с использованием lambda-функции
df['Age_category'] = df['Age'].apply(lambda age: 'Young' if age < 30 else 'Middle-aged' if 30 <= age < 40 else 'Senior')

In [ ]:
# Запомните разницу:

# .apply(lambda x: ...) — вызывается для конкретного столбца дата-фрейма и работает по значениям только этого столбца;

#.apply(lambda row: ..., axis=1) — вызывается для всего дата-фрейма целиком и поэтому внутрь row передается вся строка дата-фрейма,
#благодаря чему можно обращаться к нескольким столбцам сразу. Обратите внимание что в таком случае указываем axis=1)

In [7]:
# Метод .apply() позволяет применять функцию к каждому элементу в Series (столбце).

# Применим функцию, чтобы получить квадрат возраста
import pandas as pd

# Создаем DataFrame
data = {
    'Имя': ['Аня', 'Борис', 'Света'],
    'Возраст': [23, 34, 29],  # Возраст представлен строками
    'Рост': [1.65, 1.80, 1.75]  # Рост тоже строками
}

df = pd.DataFrame(data)

df['Возраст_квадрат'] = df['Возраст'].apply(lambda x: x ** 2)
print(df)

     Имя  Возраст  Рост  Возраст_квадрат
0    Аня       23  1.65              529
1  Борис       34  1.80             1156
2  Света       29  1.75              841

In [ ]:
df[['Рост']] = df[['Рост']].apply(lambda x: round(x, 1))
print(df)

     Имя  Возраст  Рост  Возраст_квадрат  Сумма
0    Аня       23   1.6              529  24.65
1  Борис       34   1.8             1156  35.80
2  Света       29   1.8              841  30.75

In [3]:
# Применение функции к каждой строке или столбцу.

# Суммируем значения в строках
df['Сумма'] = df.apply(lambda row: row['Возраст'] + row['Рост'], axis=1)  # axis=1 означает, что функция применяется к строкам
print(df)

     Имя  Возраст  Рост  Возраст_квадрат  Сумма
0    Аня       23  1.65              529  24.65
1  Борис       34  1.80             1156  35.80
2  Света       29  1.75              841  30.75

### map()

__map()__ позволяет применять функцию к каждому элементу в Series.\
__map()__ применяется для преобразования данных с помощью словаря, чаще всего для замены определенных значений

In [ ]:
df['Occupation_short'].values

In [ ]:
df['Occupation_short'] = df['Occupation'].map({
    'Data Analyst': 'DA',
    'Software Dev': 'SD',
    'Project Manager': 'PM',
    'HR Specialist': 'HR',
    'Data Scientist': 'DS',
    'Business Analyst': 'BA',
    'Chief Technology Officer': 'CTO'
})

In [ ]:
df['Occupation_short'].values

array(['DA', 'SD', 'PM', 'DS', 'HR', 'BA', nan, 'DA', 'SD', 'PM', 'HR',
       'DS', 'BA', nan, 'DA', 'SD', 'PM', 'DS', 'HR', nan, 'BA', 'PM',
       'SD', 'HR', 'DS', 'BA', 'DA', 'PM', 'SD', 'HR', 'DS', nan, 'BA',
       'PM', 'DS', nan, 'SD', 'HR', 'DA', 'PM', 'SD', 'HR', 'DS', nan,
       'BA', 'PM', 'DS', 'BA', 'SD'], dtype=object)

In [ ]:
# Применяем функцию для преобразования имен в верхний регистр
df['Имя'] = df['Имя'].map(lambda x: x.upper())
print(df)

## Скользящие окна

**Скользящие окна** – это инструмент, который используется для вычисления статистических метрик (таких как сумма или медиана) на основе окон данных определенной оси, которые движутся по временной оси.

В Pandas реализованы в методе **rolling()**. Его аргумент *window=* отвечает за размер окна. Рассмотрим работу функции на примере, вычислим среднее с помощью окна с размером в 5 дней:

In [ ]:
df = pd.read_csv('https://drive.google.com/uc?export=download&id=1c0afct7xI5Nh2LW3uQ7itHYlan9CirZ-', parse_dates=['Date'])

In [ ]:
df['Rolling mean'] = df['Sales'].rolling(window=5).mean()

In [ ]:
df.head(10)

        Date         Category  Sales  Discount  Rolling mean
0 2024-01-01      Electronics    200         0           NaN
1 2024-01-02      Electronics    220         5           NaN
2 2024-01-03      Electronics    250        10           NaN
3 2024-01-04  Home Appliances    180         0           NaN
4 2024-01-05  Home Appliances    160         0         202.0
5 2024-01-06      Electronics    230         5         208.0
6 2024-01-07         Clothing    120        15         188.0
7 2024-01-08         Clothing    150        10         168.0
8 2024-01-09  Home Appliances    200         5         172.0
9 2024-01-10         Clothing    160        20         172.0